<?php
/** 
 * @file
 * A proof of concept of the use of tablesort.js
 * https://github.com/tristen/tablesort
 * 
 * This is hard-coded to attach the library to a table with ID "table-tablesort".
 * This table MUST exist in the body field of a node
 */

/**
 * Implements hook_node_view().
 */
function tablesort_poc_node_view($node) {

  // Change this variable to match the DOM ID of the table.
  $table_id = 'table-tablesort';
  
  if (isset($node->body) && strpos($node->body[LANGUAGE_NONE][0]['value'], $table_id) !== FALSE) {
    $path = backdrop_get_path('module', 'tablesort_poc');

    // Attach the js and css libraries.
    $node->content['#attached']['css'][] = $path . '/css/tablesort.css';
    $node->content['#attached']['js'][] = $path . '/js/tablesort.min.js';
    $node->content['#attached']['js'][] = $path . '/js/sorts/tablesort.number.min.js';
    $node->content['#attached']['js'][] = $path . '/js/sorts/tablesort.monthname.min.js';
    
    // Send the table ID as a setting to the js triggering script. See tablesort_trigger.js
    $node->content['#attached']['js'][] = array(
      'type' => 'setting',
      'data' => array(
        'tablesort_poc' => array(
          'table_id' => $table_id,
        ),
      ),
    );

    // Attach the triggering js script.
    $node->content['#attached']['js'][] = $path . '/js/tablesort_trigger.js';
  }
}
